# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x16\n\x07Request\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\"\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\x05\x32\xbb\x01\n\x04\x45\x63ho\x12&\n\x05Unary\x12\r.echo.Request\x1a\x0e.echo.Response\x12/\n\x0cServerStream\x12\r.echo.Request\x1a\x0e.echo.Response0\x01\x12/\n\x0c\x43lientStream\x12\r.echo.Request\x1a\x0e.echo.Response(\x01\x12)\n\x04\x42idi\x12\r.echo.Request\x1a\x0e.echo.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=42
  _globals['_RESPONSE']._serialized_start=44
  _globals['_RESPONSE']._serialized_end=78
  _globals['_ECHO']._serialized_start=81
  _globals['_ECHO']._serialized_end=268
# @@protoc_insertion_point(module_scope)
